### PR TITLE
added initial x64 version

### PR DESCRIPTION
**Pull request by chcg**
- corrected typo in README.md
- enable vcxproj for x64, enabled DEP and ASLR
- initial x64 adaptations

, see https://ci.appveyor.com/project/chcg/elastictabstops/build/1.1.5 on the open compiler issue with x64, leading to build errors for x64 release builds. No appveyor.yml config contained in this PR hoping that is what you expect.

### CODE REVIEW

**Comment by dail8859** [comment]
Hi @chcg. Thanks for the PR.

All these changes seem fine except for using `%zd`. Editing the settings file shows `padding zd` which I'm assuming is Microsoft's compiler not liking the `%zd` format specifier. It looks like they [recommend](https://msdn.microsoft.com/en-us/library/tcxf1dw6(v=vs.120).aspx) using `%Iu` which seems to work fine for me.

If you are ok with this change, I can handle this myself or you can update the PR, either way is fine with me.

**Comment by chcg** [comment]
Just followed the suggestion of the compiler warning, but min_padding has type size_t, so something with %u should be used.

If it should be portable to gcc/mingw then %zu might be the better choice at least for VS2013 update 4 and newer, see https://stackoverflow.com/questions/2524611/how-can-one-print-a-size-t-variable-portably-using-the-printf-family.

@dail8859 Which one do you like more? I will change the PR.

**Comment by dail8859** [comment]
> If it should be portable to gcc/mingw then %zu might be the better choice

I'm not worried about portability. AFAICT Microsoft doesn't support `%zu` for VS2013, and VS2015 support is completely undocumented. 

So either `%Iu` would work...or honestly I'd be fine with changing the `size_t` to some other data type that is more "format-friendly".

**Comment by chcg** [comment]
Changed to %Iu.

See http://www.cplusplus.com/reference/cstdio/printf/ for %zu, support should come with c99 and c++11 compatibility.

**Comment by dail8859** [comment]
Thanks for the update.

> support should come with c99 and c++11 compatibility

I'm aware they are part of the standard, however Microsoft doesn't always fully support standards. ;)

**Comment by dail8859** [comment]
Oh...it looks like the Toolset got changed to `v140_xp`. Could you change that back? `vs120_xp` is fine

**Comment by chcg** [comment]
@dail8859 Sorry, that was not intended. Just overlooked that change before clicking amend, because I recompiled with vs2015 to test the %Iu. Thanks.

**Comment by dail8859** [comment]
No problem. Everything looks fine now. Thanks for the PR.

**Pull request merged**
